const defaultState = [
    {
        "title": "АТП-12",
        "text": "ИНН 5034050129,Московская обл, г Орехово-Зуево, Малодубенское шоссе, д 28",
        "fullInfo": {
            "company": {
                "kpp": "503401001",
                "capital": null,
                "management": {
                    "name": "Ильичев Роман Сергеевич",
                    "post": "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
                    "disqualified": null
                },
                "founders": null,
                "managers": null,
                "predecessors": null,
                "successors": null,
                "branch_type": "MAIN",
                "branch_count": 0,
                "source": null,
                "qc": null,
                "hid": "a0561cc7792444698bf76b803142fa18bf0b4b6f9983ff5034d540a4e02eb47e",
                "type": "LEGAL",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1642032000000,
                    "registration_date": 726883200000,
                    "liquidation_date": null
                },
                "opf": {
                    "type": "2014",
                    "code": "12247",
                    "full": "Публичное акционерное общество",
                    "short": "ПАО"
                },
                "name": {
                    "full_with_opf": "ОТКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО \"АВТОТРАНСПОРТНОЕ ПРЕДПРИЯТИЕ №12\"",
                    "short_with_opf": "ОАО \"АТП-12\"",
                    "latin": null,
                    "full": "АВТОТРАНСПОРТНОЕ ПРЕДПРИЯТИЕ №12",
                    "short": "АТП-12"
                },
                "inn": "5034050129",
                "ogrn": "1035007002238",
                "okpo": "04002390",
                "okato": "46457000000",
                "oktmo": "46757000001",
                "okogu": "4210008",
                "okfs": "16",
                "okved": "52.29",
                "okveds": null,
                "authorities": null,
                "documents": null,
                "licenses": null,
                "finance": {
                    "tax_system": null,
                    "income": null,
                    "expense": null,
                    "debt": null,
                    "penalty": null,
                    "year": null
                },
                "address": {
                    "value": "Московская обл, г Орехово-Зуево, Малодубенское шоссе, д 28",
                    "unrestricted_value": "142605, Московская обл, г Орехово-Зуево, Малодубенское шоссе, д 28",
                    "data": {
                        "postal_code": "142605",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Центральный",
                        "region_fias_id": "29251dcf-00a1-4e34-98d4-5c47484a36d4",
                        "region_kladr_id": "5000000000000",
                        "region_iso_code": "RU-MOS",
                        "region_with_type": "Московская обл",
                        "region_type": "обл",
                        "region_type_full": "область",
                        "region": "Московская",
                        "area_fias_id": "0f2f2d09-8e7a-4356-bd4d-0b055d802e7b",
                        "area_kladr_id": "5000100000000",
                        "area_with_type": "г Орехово-Зуево",
                        "area_type": "г",
                        "area_type_full": "город",
                        "area": "Орехово-Зуево",
                        "city_fias_id": "0f2f2d09-8e7a-4356-bd4d-0b055d802e7b",
                        "city_kladr_id": "5000100000000",
                        "city_with_type": "г Орехово-Зуево",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Орехово-Зуево",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": null,
                        "city_district_type": null,
                        "city_district_type_full": null,
                        "city_district": null,
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "82070b0b-04ec-4a39-8bf9-73a6fe690613",
                        "street_kladr_id": "50001000000018500",
                        "street_with_type": "Малодубенское шоссе",
                        "street_type": "ш",
                        "street_type_full": "шоссе",
                        "street": "Малодубенское",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "3d13cae7-7eb8-46fa-8d01-cce721ea0df2",
                        "house_kladr_id": "5000100000001850015",
                        "house_cadnum": null,
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "28",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": null,
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "3d13cae7-7eb8-46fa-8d01-cce721ea0df2",
                        "fias_code": "50001000000000001850015",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "5000100000001850015",
                        "geoname_id": "524925",
                        "capital_marker": "0",
                        "okato": "46457000000",
                        "oktmo": "46757000001",
                        "tax_office": "5034",
                        "tax_office_legal": "5034",
                        "timezone": "UTC+3",
                        "geo_lat": "55.8348677",
                        "geo_lon": "38.9701038",
                        "beltway_hit": "OUT_MKAD",
                        "beltway_distance": "71",
                        "metro": null,
                        "qc_geo": "0",
                        "qc_complete": null,
                        "qc_house": null,
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "142605, ОБЛАСТЬ МОСКОВСКАЯ, Г ОРЕХОВО-ЗУЕВО, Ш. МАЛОДУБЕНСКОЕ, Д.28",
                        "qc": "0"
                    }
                },
                "phones": null,
                "emails": null,
                "ogrn_date": 1046217600000,
                "okved_type": "2014",
                "employee_count": null,
                "actual_address": "Московская обл, г Орехово-Зуево, Малодубенское шоссе, д 28"
            },
            "bank": {
                "opf": {
                    "type": "BANK",
                    "full": null,
                    "short": null
                },
                "name": {
                    "payment": "\"СИБСОЦБАНК\" ООО",
                    "full": null,
                    "short": "«СИБСОЦБАНК» ООО"
                },
                "bic": "040173745",
                "swift": "SISNRU55XXX",
                "inn": "2224009042",
                "kpp": "222101001",
                "okpo": null,
                "correspondent_account": "30101810800000000745",
                "treasury_accounts": null,
                "registration_number": "2015",
                "payment_city": "г Барнаул",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1643932800000,
                    "registration_date": 714355200000,
                    "liquidation_date": null
                },
                "rkc": null,
                "cbr": null,
                "address": {
                    "value": "г Барнаул, пр-кт Ленина, д 61А",
                    "unrestricted_value": "656049, Алтайский край, г Барнаул, Железнодорожный р-н, пр-кт Ленина, д 61А",
                    "data": {
                        "postal_code": "656049",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Сибирский",
                        "region_fias_id": "8276c6a1-1a86-4f0d-8920-aba34d4cc34a",
                        "region_kladr_id": "2200000000000",
                        "region_iso_code": "RU-ALT",
                        "region_with_type": "Алтайский край",
                        "region_type": "край",
                        "region_type_full": "край",
                        "region": "Алтайский",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "d13945a8-7017-46ab-b1e6-ede1e89317ad",
                        "city_kladr_id": "2200000100000",
                        "city_with_type": "г Барнаул",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Барнаул",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": "Железнодорожный р-н",
                        "city_district_type": "р-н",
                        "city_district_type_full": "район",
                        "city_district": "Железнодорожный",
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "996a4480-4953-4178-b4e8-8333348ecda4",
                        "street_kladr_id": "22000001000035900",
                        "street_with_type": "пр-кт Ленина",
                        "street_type": "пр-кт",
                        "street_type_full": "проспект",
                        "street": "Ленина",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "6f2c4a16-971d-4b79-a504-99926bfbff6a",
                        "house_kladr_id": "2200000100003590281",
                        "house_cadnum": "22:63:040423:29",
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "61А",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": null,
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "6f2c4a16-971d-4b79-a504-99926bfbff6a",
                        "fias_code": "22000001000000003590281",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "2200000100003590281",
                        "geoname_id": "1510853",
                        "capital_marker": "2",
                        "okato": "01401363000",
                        "oktmo": "01701000001",
                        "tax_office": "2223",
                        "tax_office_legal": "2223",
                        "timezone": "UTC+7",
                        "geo_lat": "53.34752",
                        "geo_lon": "83.77565",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": null,
                        "qc_geo": "0",
                        "qc_complete": "5",
                        "qc_house": "2",
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "656049, г Барнаул, пр-т Ленина, 61 А",
                        "qc": "0"
                    }
                },
                "phones": null,
                "settlement_account": "12"
            },
            "inn": "12",
            "bic": "2"
        },
        "inn": "5034050129"
    },
    {
        "title": "БОРУС 2318",
        "text": "ИНН 2016005223,г Грозный, ул Старопромысловское шоссе, д 21",
        "fullInfo": {
            "company": {
                "kpp": "201601001",
                "capital": null,
                "management": {
                    "name": "Пастушенко Эмилия Александровна",
                    "post": "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
                    "disqualified": null
                },
                "founders": null,
                "managers": null,
                "predecessors": null,
                "successors": null,
                "branch_type": "MAIN",
                "branch_count": 0,
                "source": null,
                "qc": null,
                "hid": "7ca95bf365b84e16d8b64ef96031d2d686e0da1d0b889ec7ebf01e8099caf3ad",
                "type": "LEGAL",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1608508800000,
                    "registration_date": 1581897600000,
                    "liquidation_date": null
                },
                "opf": {
                    "type": "2014",
                    "code": "12300",
                    "full": "Общество с ограниченной ответственностью",
                    "short": "ООО"
                },
                "name": {
                    "full_with_opf": "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"БОРУС 2318\"",
                    "short_with_opf": "ООО \"БОРУС 2318\"",
                    "latin": null,
                    "full": "БОРУС 2318",
                    "short": "БОРУС 2318"
                },
                "inn": "2016005223",
                "ogrn": "1202000001389",
                "okpo": "43481381",
                "okato": "96401364000",
                "oktmo": "96701000001",
                "okogu": "4210014",
                "okfs": "16",
                "okved": "46.73",
                "okveds": null,
                "authorities": null,
                "documents": null,
                "licenses": null,
                "finance": {
                    "tax_system": null,
                    "income": null,
                    "expense": null,
                    "debt": null,
                    "penalty": null,
                    "year": null
                },
                "address": {
                    "value": "г Грозный, ул Старопромысловское шоссе, д 21",
                    "unrestricted_value": "364020, Чеченская Респ, г Грозный, ул Старопромысловское шоссе, д 21",
                    "data": {
                        "postal_code": "364020",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Северо-Кавказский",
                        "region_fias_id": "de67dc49-b9ba-48a3-a4cc-c2ebfeca6c5e",
                        "region_kladr_id": "2000000000000",
                        "region_iso_code": "RU-CE",
                        "region_with_type": "Чеченская Респ",
                        "region_type": "Респ",
                        "region_type_full": "республика",
                        "region": "Чеченская",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "a2072dc5-45be-4db3-ab13-10784ba8b2ae",
                        "city_kladr_id": "2000000100000",
                        "city_with_type": "г Грозный",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Грозный",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": null,
                        "city_district_type": null,
                        "city_district_type_full": null,
                        "city_district": null,
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "68f94de0-bc70-4fb5-8f6e-800fc642e3ed",
                        "street_kladr_id": "20000001000148900",
                        "street_with_type": "ул Старопромысловское шоссе",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "Старопромысловское шоссе",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "73b684a2-131d-4e9a-944c-fc51613e7eee",
                        "house_kladr_id": "2000000100014890010",
                        "house_cadnum": null,
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "21",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": null,
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "73b684a2-131d-4e9a-944c-fc51613e7eee",
                        "fias_code": "20000001000000014890010",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "2000000100014890010",
                        "geoname_id": "558418",
                        "capital_marker": "2",
                        "okato": "96401360000",
                        "oktmo": "96701000001",
                        "tax_office": "2000",
                        "tax_office_legal": "2000",
                        "timezone": "UTC+3",
                        "geo_lat": "43.3333326",
                        "geo_lon": "45.674447",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": null,
                        "qc_geo": "2",
                        "qc_complete": null,
                        "qc_house": null,
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "364020, РЕСПУБЛИКА ЧЕЧЕНСКАЯ, Г. ГРОЗНЫЙ, УЛ. СТАРОПРОМЫСЛОВСКОЕ ШОССЕ, Д. 21",
                        "qc": "0"
                    }
                },
                "phones": null,
                "emails": null,
                "ogrn_date": 1581897600000,
                "okved_type": "2014",
                "employee_count": null,
                "actual_address": "г Грозный, ул Старопромысловское шоссе, д 21"
            },
            "bank": {
                "opf": {
                    "type": "BANK",
                    "full": null,
                    "short": null
                },
                "name": {
                    "payment": "\"СЕВЕРСТРОЙБАНК\" АО",
                    "full": null,
                    "short": "«СеверСтройБанк» АО"
                },
                "bic": "041909707",
                "swift": null,
                "inn": "3525269550",
                "kpp": "352501001",
                "okpo": null,
                "correspondent_account": "30101810300000000707",
                "treasury_accounts": null,
                "registration_number": "3507",
                "payment_city": "г Вологда",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1643932800000,
                    "registration_date": 1331424000000,
                    "liquidation_date": null
                },
                "rkc": null,
                "cbr": null,
                "address": {
                    "value": "г Вологда, ул Мальцева, д 52",
                    "unrestricted_value": "160009, Вологодская обл, г Вологда, ул Мальцева, д 52",
                    "data": {
                        "postal_code": "160009",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Северо-Западный",
                        "region_fias_id": "ed36085a-b2f5-454f-b9a9-1c9a678ee618",
                        "region_kladr_id": "3500000000000",
                        "region_iso_code": "RU-VLG",
                        "region_with_type": "Вологодская обл",
                        "region_type": "обл",
                        "region_type_full": "область",
                        "region": "Вологодская",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "023484a5-f98d-4849-82e1-b7e0444b54ef",
                        "city_kladr_id": "3500000100000",
                        "city_with_type": "г Вологда",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Вологда",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": null,
                        "city_district_type": null,
                        "city_district_type_full": null,
                        "city_district": null,
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "246c7db3-2152-4af5-b7b0-9395f0a06b32",
                        "street_kladr_id": "35000001000015800",
                        "street_with_type": "ул Мальцева",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "Мальцева",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "9a0f1945-cb3b-48c0-8bcc-7d921f20ea03",
                        "house_kladr_id": "3500000100001580029",
                        "house_cadnum": null,
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "52",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": "315.2",
                        "square_meter_price": null,
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "9a0f1945-cb3b-48c0-8bcc-7d921f20ea03",
                        "fias_code": "35000001000000001580029",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "3500000100001580029",
                        "geoname_id": "472459",
                        "capital_marker": "2",
                        "okato": "19401000000",
                        "oktmo": "19701000001",
                        "tax_office": "3525",
                        "tax_office_legal": "3525",
                        "timezone": "UTC+3",
                        "geo_lat": "59.214582",
                        "geo_lon": "39.8727192",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": null,
                        "qc_geo": "0",
                        "qc_complete": "5",
                        "qc_house": "2",
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "160009, г Вологда, ул Мальцева, 52",
                        "qc": "0"
                    }
                },
                "phones": null,
                "settlement_account": "412"
            },
            "inn": "231",
            "bic": "3"
        },
        "inn": "2016005223"
    },
    {
        "title": "АПТЕКА 5",
        "text": "ИНН 6315245781,г Самара, ул Самарская, д 203",
        "fullInfo": {
            "company": {
                "kpp": "631501001",
                "capital": null,
                "management": {
                    "name": "Будников Игорь Михайлович",
                    "post": "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
                    "disqualified": null
                },
                "founders": null,
                "managers": null,
                "predecessors": null,
                "successors": null,
                "branch_type": "MAIN",
                "branch_count": 0,
                "source": null,
                "qc": null,
                "hid": "830d83b2f2733af7cb2d733a27c474cff9dd090e4297092c90983dd6e58d7801",
                "type": "LEGAL",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1584921600000,
                    "registration_date": 908755200000,
                    "liquidation_date": null
                },
                "opf": {
                    "type": "2014",
                    "code": "12247",
                    "full": "Публичное акционерное общество",
                    "short": "ПАО"
                },
                "name": {
                    "full_with_opf": "ОТКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО \"АПТЕКА 5\"",
                    "short_with_opf": "ОАО \"АПТЕКА 5\"",
                    "latin": null,
                    "full": "АПТЕКА 5",
                    "short": "АПТЕКА 5"
                },
                "inn": "6315245781",
                "ogrn": "1026300971894",
                "okpo": "20963781",
                "okato": "36401383000",
                "oktmo": "36701325000",
                "okogu": "4210008",
                "okfs": "16",
                "okved": "68.20",
                "okveds": null,
                "authorities": null,
                "documents": null,
                "licenses": null,
                "finance": {
                    "tax_system": null,
                    "income": null,
                    "expense": null,
                    "debt": null,
                    "penalty": null,
                    "year": null
                },
                "address": {
                    "value": "г Самара, ул Самарская, д 203",
                    "unrestricted_value": "443001, Самарская обл, г Самара, Ленинский р-н, ул Самарская, д 203",
                    "data": {
                        "postal_code": "443001",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Приволжский",
                        "region_fias_id": "df3d7359-afa9-4aaa-8ff9-197e73906b1c",
                        "region_kladr_id": "6300000000000",
                        "region_iso_code": "RU-SAM",
                        "region_with_type": "Самарская обл",
                        "region_type": "обл",
                        "region_type_full": "область",
                        "region": "Самарская",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "bb035cc3-1dc2-4627-9d25-a1bf2d4b936b",
                        "city_kladr_id": "6300000100000",
                        "city_with_type": "г Самара",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Самара",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": "Ленинский р-н",
                        "city_district_type": "р-н",
                        "city_district_type_full": "район",
                        "city_district": "Ленинский",
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "d6cd1d0a-66e5-4124-a474-f3ebcf2a0264",
                        "street_kladr_id": "63000001000072300",
                        "street_with_type": "ул Самарская",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "Самарская",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "d8922b53-d668-4287-a7b4-011af0330ac1",
                        "house_kladr_id": "6300000100007230199",
                        "house_cadnum": null,
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "203",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": "77760",
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "d8922b53-d668-4287-a7b4-011af0330ac1",
                        "fias_code": "63000001000000007230199",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "6300000100007230199",
                        "geoname_id": "499099",
                        "capital_marker": "2",
                        "okato": "36401383000",
                        "oktmo": "36701325",
                        "tax_office": "6317",
                        "tax_office_legal": "6317",
                        "timezone": "UTC+4",
                        "geo_lat": "53.199562",
                        "geo_lon": "50.112635",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": [
                            {
                                "name": "Алабинская",
                                "line": "Первая",
                                "distance": 1.8
                            },
                            {
                                "name": "Российская",
                                "line": "Первая",
                                "distance": 2.8
                            },
                            {
                                "name": "Московская",
                                "line": "Первая",
                                "distance": 3.2
                            }
                        ],
                        "qc_geo": "0",
                        "qc_complete": null,
                        "qc_house": null,
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "443001, ОБЛАСТЬ САМАРСКАЯ, Г. САМАРА, УЛ. САМАРСКАЯ, Д.203",
                        "qc": "0"
                    }
                },
                "phones": null,
                "emails": null,
                "ogrn_date": 1040342400000,
                "okved_type": "2014",
                "employee_count": null,
                "actual_address": "г Самара, ул Самарская, д 203"
            },
            "bank": {
                "opf": {
                    "type": "BANK",
                    "full": null,
                    "short": null
                },
                "name": {
                    "payment": "АО НОКССБАНК",
                    "full": null,
                    "short": "АО НОКССБАНК"
                },
                "bic": "041806831",
                "swift": "NOKSRU2VXXX",
                "inn": "3442028061",
                "kpp": "344401001",
                "okpo": null,
                "correspondent_account": "30101810000000000831",
                "treasury_accounts": null,
                "registration_number": "3202",
                "payment_city": "г Волгоград",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1643932800000,
                    "registration_date": 790992000000,
                    "liquidation_date": null
                },
                "rkc": null,
                "cbr": null,
                "address": {
                    "value": "г Волгоград, ул 7-й Гвардейской, д 2",
                    "unrestricted_value": "400005, Волгоградская обл, г Волгоград, Центральный р-н, ул 7-й Гвардейской, д 2",
                    "data": {
                        "postal_code": "400005",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Южный",
                        "region_fias_id": "da051ec8-da2e-4a66-b542-473b8d221ab4",
                        "region_kladr_id": "3400000000000",
                        "region_iso_code": "RU-VGG",
                        "region_with_type": "Волгоградская обл",
                        "region_type": "обл",
                        "region_type_full": "область",
                        "region": "Волгоградская",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "a52b7389-0cfe-46fb-ae15-298652a64cf8",
                        "city_kladr_id": "3400000100000",
                        "city_with_type": "г Волгоград",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Волгоград",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": "Центральный р-н",
                        "city_district_type": "р-н",
                        "city_district_type_full": "район",
                        "city_district": "Центральный",
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "c21bd04b-b450-4feb-a34c-a3d9b8a4e4ba",
                        "street_kladr_id": "34000001000077000",
                        "street_with_type": "ул 7-й Гвардейской",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "7-й Гвардейской",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "22519be9-254d-41e2-87ae-42bd06be84b0",
                        "house_kladr_id": "3400000100007700006",
                        "house_cadnum": "34:34:040016:348",
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "2",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": "66071",
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "22519be9-254d-41e2-87ae-42bd06be84b0",
                        "fias_code": "34000001000000007700006",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "3400000100007700006",
                        "geoname_id": "472757",
                        "capital_marker": "2",
                        "okato": "18401395000",
                        "oktmo": "18701000001",
                        "tax_office": "3444",
                        "tax_office_legal": "3444",
                        "timezone": "UTC+3",
                        "geo_lat": "48.7216571",
                        "geo_lon": "44.5381237",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": null,
                        "qc_geo": "0",
                        "qc_complete": "5",
                        "qc_house": "2",
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "400005, г Волгоград, ул 7-ой Гвардейской, 2",
                        "qc": "0"
                    }
                },
                "phones": null,
                "settlement_account": "35"
            },
            "inn": "5",
            "bic": "34"
        },
        "inn": "6315245781"
    },
    {
        "title": "УНР - 543",
        "text": "ИНН 7733543547,г Москва, ул Маршала Рыбалко, д 9, кв 37",
        "fullInfo": {
            "company": {
                "kpp": "773401001",
                "capital": null,
                "management": {
                    "name": "Левченко Ольга Евгеньевна",
                    "post": "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР",
                    "disqualified": null
                },
                "founders": null,
                "managers": null,
                "predecessors": null,
                "successors": null,
                "branch_type": "MAIN",
                "branch_count": 0,
                "source": null,
                "qc": null,
                "hid": "a6209e804658bdd093c63db6d28e63abf6cc5909021d1671dcef7bc5d2dcba50",
                "type": "LEGAL",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1600387200000,
                    "registration_date": 1116201600000,
                    "liquidation_date": null
                },
                "opf": {
                    "type": "2014",
                    "code": "12300",
                    "full": "Общество с ограниченной ответственностью",
                    "short": "ООО"
                },
                "name": {
                    "full_with_opf": "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"УСПЕХ НАШЕЙ РАБОТЫ - 543\"",
                    "short_with_opf": "ООО \"УНР - 543\"",
                    "latin": null,
                    "full": "УСПЕХ НАШЕЙ РАБОТЫ - 543",
                    "short": "УНР - 543"
                },
                "inn": "7733543547",
                "ogrn": "1057747011178",
                "okpo": "77483196",
                "okato": "45283587000",
                "oktmo": "45372000000",
                "okogu": "4210014",
                "okfs": "16",
                "okved": "43.12",
                "okveds": null,
                "authorities": null,
                "documents": null,
                "licenses": null,
                "finance": {
                    "tax_system": null,
                    "income": null,
                    "expense": null,
                    "debt": null,
                    "penalty": null,
                    "year": null
                },
                "address": {
                    "value": "г Москва, ул Маршала Рыбалко, д 9, кв 37",
                    "unrestricted_value": "123060, г Москва, р-н Щукино, ул Маршала Рыбалко, д 9, кв 37",
                    "data": {
                        "postal_code": "123060",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Центральный",
                        "region_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                        "region_kladr_id": "7700000000000",
                        "region_iso_code": "RU-MOW",
                        "region_with_type": "г Москва",
                        "region_type": "г",
                        "region_type_full": "город",
                        "region": "Москва",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "0c5b2444-70a0-4932-980c-b4dc0d3f02b5",
                        "city_kladr_id": "7700000000000",
                        "city_with_type": "г Москва",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Москва",
                        "city_area": "Северо-западный",
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": "р-н Щукино",
                        "city_district_type": "р-н",
                        "city_district_type_full": "район",
                        "city_district": "Щукино",
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "85adf5f7-168b-45d0-b11f-03c2236b22d9",
                        "street_kladr_id": "77000000000252300",
                        "street_with_type": "ул Маршала Рыбалко",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "Маршала Рыбалко",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "3626cdfd-1dfb-4fe7-ac9e-ac7d1f9a592b",
                        "house_kladr_id": "7700000000025230032",
                        "house_cadnum": null,
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "9",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": "кв",
                        "flat_type_full": "квартира",
                        "flat": "37",
                        "flat_area": "82.4",
                        "square_meter_price": "183177",
                        "flat_price": "15093785",
                        "postal_box": null,
                        "fias_id": "3626cdfd-1dfb-4fe7-ac9e-ac7d1f9a592b",
                        "fias_code": "77000000000000025230032",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "7700000000025230032",
                        "geoname_id": "524901",
                        "capital_marker": "0",
                        "okato": "45283587000",
                        "oktmo": "45372000",
                        "tax_office": "7734",
                        "tax_office_legal": "7734",
                        "timezone": "UTC+3",
                        "geo_lat": "55.7973125",
                        "geo_lon": "37.4904215",
                        "beltway_hit": "IN_MKAD",
                        "beltway_distance": null,
                        "metro": [
                            {
                                "name": "Октябрьское поле",
                                "line": "Таганско-Краснопресненская",
                                "distance": 0.5
                            },
                            {
                                "name": "Панфиловская",
                                "line": "МЦК",
                                "distance": 0.6
                            },
                            {
                                "name": "Зорге",
                                "line": "МЦК",
                                "distance": 1.4
                            }
                        ],
                        "qc_geo": "0",
                        "qc_complete": null,
                        "qc_house": null,
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "123060, ГОРОД МОСКВА, УЛ. МАРШАЛА РЫБАЛКО, Д. 9, КВ. 37",
                        "qc": "0"
                    }
                },
                "phones": null,
                "emails": null,
                "ogrn_date": 1116201600000,
                "okved_type": "2014",
                "employee_count": null,
                "actual_address": "г Москва, ул Маршала Рыбалко, д 9, кв 37"
            },
            "bank": {
                "opf": {
                    "type": "BANK",
                    "full": null,
                    "short": null
                },
                "name": {
                    "payment": "АО \"БАНК АКЦЕПТ\"",
                    "full": null,
                    "short": "АО «Банк Акцепт»"
                },
                "bic": "045004815",
                "swift": "AJSCRU55XXX",
                "inn": "5405114781",
                "kpp": "540601001",
                "okpo": null,
                "correspondent_account": "30101810200000000815",
                "treasury_accounts": null,
                "registration_number": "567",
                "payment_city": "г Новосибирск",
                "state": {
                    "status": "ACTIVE",
                    "code": null,
                    "actuality_date": 1643932800000,
                    "registration_date": 656726400000,
                    "liquidation_date": null
                },
                "rkc": null,
                "cbr": null,
                "address": {
                    "value": "г Новосибирск, ул Советская, д 14",
                    "unrestricted_value": "630099, Новосибирская обл, г Новосибирск, Центральный р-н, ул Советская, д 14",
                    "data": {
                        "postal_code": "630099",
                        "country": "Россия",
                        "country_iso_code": "RU",
                        "federal_district": "Сибирский",
                        "region_fias_id": "1ac46b49-3209-4814-b7bf-a509ea1aecd9",
                        "region_kladr_id": "5400000000000",
                        "region_iso_code": "RU-NVS",
                        "region_with_type": "Новосибирская обл",
                        "region_type": "обл",
                        "region_type_full": "область",
                        "region": "Новосибирская",
                        "area_fias_id": null,
                        "area_kladr_id": null,
                        "area_with_type": null,
                        "area_type": null,
                        "area_type_full": null,
                        "area": null,
                        "city_fias_id": "8dea00e3-9aab-4d8e-887c-ef2aaa546456",
                        "city_kladr_id": "5400000100000",
                        "city_with_type": "г Новосибирск",
                        "city_type": "г",
                        "city_type_full": "город",
                        "city": "Новосибирск",
                        "city_area": null,
                        "city_district_fias_id": null,
                        "city_district_kladr_id": null,
                        "city_district_with_type": "Центральный р-н",
                        "city_district_type": "р-н",
                        "city_district_type_full": "район",
                        "city_district": "Центральный",
                        "settlement_fias_id": null,
                        "settlement_kladr_id": null,
                        "settlement_with_type": null,
                        "settlement_type": null,
                        "settlement_type_full": null,
                        "settlement": null,
                        "street_fias_id": "59b5d01a-ddf7-4c44-b49b-77cc197a1d6f",
                        "street_kladr_id": "54000001000124400",
                        "street_with_type": "ул Советская",
                        "street_type": "ул",
                        "street_type_full": "улица",
                        "street": "Советская",
                        "stead_fias_id": null,
                        "stead_cadnum": null,
                        "stead_type": null,
                        "stead_type_full": null,
                        "stead": null,
                        "house_fias_id": "3d8d8522-ad1e-4b0a-944a-9dcfec01bdb4",
                        "house_kladr_id": "5400000100012440014",
                        "house_cadnum": "54:35:101450:259",
                        "house_type": "д",
                        "house_type_full": "дом",
                        "house": "14",
                        "block_type": null,
                        "block_type_full": null,
                        "block": null,
                        "entrance": null,
                        "floor": null,
                        "flat_fias_id": null,
                        "flat_cadnum": null,
                        "flat_type": null,
                        "flat_type_full": null,
                        "flat": null,
                        "flat_area": null,
                        "square_meter_price": null,
                        "flat_price": null,
                        "postal_box": null,
                        "fias_id": "3d8d8522-ad1e-4b0a-944a-9dcfec01bdb4",
                        "fias_code": "54000001000000012440014",
                        "fias_level": "8",
                        "fias_actuality_state": "0",
                        "kladr_id": "5400000100012440014",
                        "geoname_id": "1496747",
                        "capital_marker": "2",
                        "okato": "50401386000",
                        "oktmo": "50701000001",
                        "tax_office": "5406",
                        "tax_office_legal": "5406",
                        "timezone": "UTC+7",
                        "geo_lat": "55.0267648",
                        "geo_lon": "82.917897",
                        "beltway_hit": null,
                        "beltway_distance": null,
                        "metro": [
                            {
                                "name": "Площадь Ленина",
                                "line": "Ленинская",
                                "distance": 0.4
                            },
                            {
                                "name": "Красный проспект",
                                "line": "Ленинская",
                                "distance": 1.6
                            },
                            {
                                "name": "Октябрьская",
                                "line": "Ленинская",
                                "distance": 1.6
                            }
                        ],
                        "qc_geo": "0",
                        "qc_complete": "5",
                        "qc_house": "2",
                        "history_values": null,
                        "unparsed_parts": null,
                        "source": "630099, г Новосибирск, ул Советская, 14",
                        "qc": "0"
                    }
                },
                "phones": null,
                "settlement_account": "345"
            },
            "inn": "543",
            "bic": "54"
        },
        "inn": "7733543547"
    }
]

const ADD_COMPANY = "ADD_COMPANY";
const REMOVE_COMPANY = "REMOVE_COMPANY"
const EDIT_COMPANY = "EDIT_COMPANY"

export const cardsReducer = (state = defaultState, action) => {
    switch (action.type) {
        case ADD_COMPANY:
            return [...state, action.payload]
        case REMOVE_COMPANY:
            return [...state.filter(card => card.inn !== action.payload)]
        case EDIT_COMPANY:
            return [...state.filter(card => card.inn !== action.payload.inn), action.payload]
        default:
            return state
    }
}

export const addCompanyAction = (payload) => ({ type: ADD_COMPANY, payload });
export const removeCompanyAction = (payload) => ({ type: REMOVE_COMPANY, payload });
export const editCompanyAction = (payload) => ({ type: EDIT_COMPANY, payload });
